// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46i1JJPwZ7xjxOaSY4MMd69divdFVsMA',
    appId: '1:824305686898:web:65d19397c222d028cae5eb',
    messagingSenderId: '824305686898',
    projectId: 'asynconf-2',
    authDomain: 'asynconf-2.firebaseapp.com',
    storageBucket: 'asynconf-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkONHxpM7CvSPFaYaRGMVjRehpT7nmkpk',
    appId: '1:824305686898:android:50c2f31f17172793cae5eb',
    messagingSenderId: '824305686898',
    projectId: 'asynconf-2',
    storageBucket: 'asynconf-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALUoBaalxJ8GRpAxEtsitcjXoFCoJ8zk',
    appId: '1:824305686898:ios:4486f7fe2601d954cae5eb',
    messagingSenderId: '824305686898',
    projectId: 'asynconf-2',
    storageBucket: 'asynconf-2.appspot.com',
    iosBundleId: 'com.example.asyncof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDALUoBaalxJ8GRpAxEtsitcjXoFCoJ8zk',
    appId: '1:824305686898:ios:4486f7fe2601d954cae5eb',
    messagingSenderId: '824305686898',
    projectId: 'asynconf-2',
    storageBucket: 'asynconf-2.appspot.com',
    iosBundleId: 'com.example.asyncof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB46i1JJPwZ7xjxOaSY4MMd69divdFVsMA',
    appId: '1:824305686898:web:c53c1b53127d0bd1cae5eb',
    messagingSenderId: '824305686898',
    projectId: 'asynconf-2',
    authDomain: 'asynconf-2.firebaseapp.com',
    storageBucket: 'asynconf-2.appspot.com',
  );
}
